# Generated by Django 2.2.28 on 2024-11-27 11:59

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
    ]
